### ISSUE TITLE
Getting missing access token even though it is present in the github secrets

### ISSUE THREAD

**Issue by aakash1313** [k-paxian/dart-package-publisher#10]
Hi,
I am trying to automate the publishing of a flutter package for which i added the access token and refresh token in the secrets. But i am still getting the error stating missing access token ? 

  - name: 'my_package'
      uses: k-paxian/dart-package-publisher@master
      with:
        skipTests: true
        dryRunOnly: true
        accessToken: ${{ secrets.ABC_OAUTH_ACCESS_TOKEN }}
        refreshToken: ${{ secrets.ABC_OAUTH_REFRESH_TOKEN }}

**Comment by k-paxian** [comment]
Make sure you have proper indentation in your yaml file
