### ISSUE TITLE
Pub needs your authorization to upload packages on your behalf-for verified publisher

### ISSUE THREAD

**Issue by lambdaR** [k-paxian/dart-package-publisher#18]
Hi, we are a verified publisher https://pub.dev/packages/m3o yet we are facing problem publishing our package automatically using this GitHub action.

Any idea what we can do to fix this issue, currently we are publishing our package manually.
below is the latest logs, you can see it is setting there waiting for an action from our side.

https://github.com/m3o/m3o-dart/runs/6195174158?check_suite_focus=true#step:9:194

and this is the workflow `publish.yml`

https://github.com/m3o/m3o-dart/blob/main/.github/workflows/publish.yml

**Comment by AlexV525** [comment]
Your credential seems to be invalid.

**Comment by k-paxian** [comment]
Please make sure you have updated your credentials after you've got verified as a publisher
