### ISSUE TITLE
Add support for Flutter packages

### ISSUE THREAD

**Issue by pavanpodila** [k-paxian/dart-package-publisher#2]
It would be great if you could also support Flutter packages. Currently it fails with the following output:

```shell
Check inputs...
OK
Switching to package directory 'flutter_mobx'
Package dir: /github/workspace/flutter_mobx
Because flutter_mobx depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
No pubspec.lock file found, please run "pub get" first.
/entrypoint.sh: line 35: lines: bad array subscript
##[error]Docker run failed with exit code 1
```

You can check if the package type is flutter by looking at the `pubspec.yaml` and seeing if there is a flutter sdk specified. For those cases, you can switch to flutter specific commands for `get`, `test` and `publish`

**Comment by pavanpodila** [comment]
Failing with this error:

```
Check inputs...
OK
Switching to package directory 'flutter_mobx'
Package dir: /github/workspace/flutter_mobx
Because flutter_mobx depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
No pubspec.lock file found, please run "pub get" first.
/entrypoint.sh: line 36: lines: bad array subscript
##[error]Docker run failed with exit code 1
```

**Comment by pavanpodila** [comment]
@k-paxian thanks to your action, I now have a completely automated workflow for `mobx` and `mobx_codegen`. Hope you can support flutter as well, so that even `flutter_mobx` can adopt your action successfully. 🚀 

https://github.com/mobxjs/mobx.dart/runs/406482560

**Comment by k-paxian** [comment]
@pavanpodila 
Please test it from `master` branch, consult with the readme how to use it.
Basically you need to add extra boolean parameter `flutter: true`.

If you'll have some troubles let me know

**Comment by pavanpodila** [comment]
Its not running the unit tests for Flutter, even though there is a dependency on `flutter_test`

```
Check inputs...
OK
Switching to package directory 'flutter_mobx'
Package dir: /github/workspace/flutter_mobx
Package: flutter_mobx
Local version: [0.3.6+1]
No unit test related dependencies detected, skip unit testing.
Remote version: [0.3.6+1]
Remote & Local versions are equal, skip publishing.
```

**Comment by pavanpodila** [comment]
I see that you are only testing for the `test` regex instead of `flutter_test`. For `flutter: true`, you should change the regex to include (flutter_test | test) ?

```
HAS_TEST=`echo "$GET" | perl -n -e'/^\+ test (.*)/ && print $1'`
```

**Comment by k-paxian** [comment]
Exactly! Thanks for noticing that.
Will fix that

**Comment by k-paxian** [comment]
should be finde now.

**Comment by pavanpodila** [comment]
Hi @k-paxian, it is still not running the unit tests. I'm running against the master.

```
No unit test related dependencies detected, skip unit testing.
```
https://github.com/mobxjs/mobx.dart/runs/409144262?check_suite_focus=true

**Comment by k-paxian** [comment]
Well, in your pubspec, you don't have specified dependency on "test". Only "flutter_test". 

And with all that. My flutter package is failing to run tests w/o "test" dependency.
https://github.com/k-paxian/dart-package-publisher/runs/409352458?check_suite_focus=true

**Comment by pavanpodila** [comment]
Woohoo! It works now. Thanks @k-paxian. We now have a fully automated flow for mobx packages!

**Comment by k-paxian** [comment]
Additionally I have added an "success" output. To find out if it is published successfully.

**Comment by pavanpodila** [comment]
cool...that is quite handy. I will use that instead. Currently I compare the local and remote versions and tag releases only if they are different.
