### ISSUE TITLE
Warning: Unexpected input(s) 'flutter'

### ISSUE THREAD

**Issue by AlexV525** [k-paxian/dart-package-publisher#20]
https://github.com/fluttercandies/flutter_wechat_assets_picker/runs/6382156800?check_suite_focus=true

When we use `flutter` in the action, jobs will report `flutter` as an unexpected input.

```
Warning: Unexpected input(s) 'flutter', valid inputs are ['entryPoint', 'args', 'accessToken', 'refreshToken', 'credentialJson', 'relativePath', 'dryRunOnly', 'skipTests', 'suppressBuildRunner', 'format']
```

**Comment by k-paxian** [comment]
That's because flutter flag is now removed and auto detected. You don't need to specify it explicitly

**Comment by AlexV525** [comment]
I don't think it's true.

Before we have the test failed without the `flutter` defined: https://github.com/AstroxNetwork/agent_dart/runs/6319818869?check_suite_focus=true

The action defined as: https://github.com/AstroxNetwork/agent_dart/blob/fca3d53a376559741fe09aae4ff833d0ac4cde92/.github/workflows/publish.yml

**Comment by k-paxian** [comment]
The real issue [here ](https://github.com/AstroxNetwork/agent_dart/runs/6319818869?check_suite_focus=true) is 
 `No package found. :(`
It's not possible to find `pubspec.yaml` it has no relation to flutter flag issue

**Comment by k-paxian** [comment]
this issue relates to https://github.com/k-paxian/dart-package-publisher/issues/19
