### ISSUE TITLE
support different flutter channel

### ISSUE THREAD

**Issue by liudonghua123** [k-paxian/dart-package-publisher#9]
I have some packages which depends `dev` channel of flutter, I find the flutter channel of this github action was hardcoded, is there any options for config the flutter channel.

**Comment by k-paxian** [comment]
PRs are welcomed!

**Comment by liudonghua123** [comment]
I forked the repo and create a new `dev` channel to build a `dev` channel of flutter docker image. 

I couldn't send PRs to a new branch of your repo.

The details of changed files is listed on https://github.com/liudonghua123/dart-package-publisher/pull/1.

**Comment by k-paxian** [comment]
added `flutterBranch` input to provide the flutter branch
